# Seminar 1

In [1]:
import cv2 as cv
import numpy as np

In [2]:
img =cv.imread("photomode_01012021_191221.png")
img =cv.resize(img, (400,400))
img2 =cv.imread("photomode_01012021_191221.png", 0)
img2 =cv.resize(img2, (400,400))

In [233]:
cv.imshow("Pic", img)
cv.imshow("Pict", img2)
cv.waitKey(0)
cv.destroyAllWindows()

In [3]:
x =int(input())
counter = 0
counter2 = 0
for i in img.reshape(-1):
    counter2+=1
    if i < x:
        counter+=1
print(counter)
print(counter2)
print(counter/counter2)

 100


138931
480000
0.2894395833333333


In [4]:
img = cv.imread("cat.png")
img =cv.resize(img, (400,400))
img2 = cv.imread("cat.png")
img2 =cv.resize(img2, (400,400))

In [5]:
# left eye
start_point = (110, 200)
end_point = (170, 250)
color=(255, 0, 0)
thickness = 2
img2 = cv.rectangle(img2, start_point, end_point, color, thickness)
# right eye
start_point = (230, 200)
end_point = (290, 250)
color=(255, 0, 0)
thickness = 2
img2 = cv.rectangle(img2, start_point, end_point, color, thickness)
# nose
center_coordinates = (200, 300)
radius = 28
color=(0, 255, 0)
img2 = cv.circle(img2, center_coordinates, radius, color, thickness)

In [6]:
# left ear
# Polygon corner points coordinates
pts = np.array([[25, 70], [40, 160], 
                [115, 80], [50, 30], 
                ],
               np.int32)
  
pts = pts.reshape((-1, 1, 2))
  
isClosed = True
  
# Blue color in BGR
color = (0, 0, 255)
  
# Line thickness of 2 px
thickness = 2
  
# Using cv2.polylines() method
# Draw a Blue polygon with 
# thickness of 1 px
img2 = cv.polylines(img2, [pts], 
                      isClosed, color, thickness)

In [7]:
# Ellipse one
radius = 100
center = (370, 90)
axes = (radius, radius)
angle = 0
startAngle = 100
endAngle = 180
img2 = cv.ellipse(img2, center, axes, angle, startAngle, endAngle, (100, 0, 100), 2)
# Ellipse two
radius = 95
center = (365, 115)
axes = (radius, radius)
angle = 90
startAngle = 100
endAngle = 180
img2 = cv.ellipse(img2, center, axes, angle, startAngle, endAngle, (100, 0, 100), 2)
# Ellipse two
radius = 50
center = (330, 70)
axes = (radius, radius)
angle = 180
startAngle = 100
endAngle = 180
img2 = cv.ellipse(img2, center, axes, angle, startAngle, endAngle, (100, 0, 100), 2)
# Ellipse two
radius = 50
center = (330, 40)
axes = (3*radius, radius)
angle = 270
startAngle = 100
endAngle = 168
img2 = cv.ellipse(img2, center, axes, angle, startAngle, endAngle, (100, 0, 100), 2)

In [8]:
cv.imshow("Pic", img2)
cv.waitKey(0)
cv.destroyAllWindows()

In [9]:
cv.imwrite("file.jpg", img)
cv.imwrite("file2.jpg", img2)

True

# Seminar 2

## Task 3

In [3]:
import cv2 as cv

In [35]:
img = cv.imread("Task3.PNG")
img2 = cv.imread("Task3.PNG", 0)

In [5]:
cv.imshow("Pic", img)
cv.waitKey(0)
cv.destroyAllWindows()

In [6]:
cv.imshow("Pic2", img2)
cv.waitKey(0)
cv.destroyAllWindows()

In [36]:
img2 =cv.adaptiveThreshold(img2, 255, cv.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY, 27, 4)

In [37]:
cv.imshow("Pic", img)
cv.imshow("Pic2", img2)
cv.waitKey(0)
cv.destroyAllWindows()

## Task 4

In [1]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
import matplotlib
def adjust_gamma(image, gamma=1.0):
	# build a lookup table mapping the pixel values [0, 255] to
	# their adjusted gamma values
	invGamma = 1.0 / gamma
	table = np.array([((i / 255.0) ** invGamma) * 255
		for i in np.arange(0, 256)]).astype("uint8")
	# apply gamma correction using the lookup table
	return cv.LUT(image, table)

In [2]:
img = cv.imread("Task5.png")
gamma = 0
alpha = int(0)
beta = int(0)

In [3]:
def plotHist(img, dst):
    hist, bins = np.histogram(img.ravel(), 256, [0, 256])
    hist = hist / hist.max() * 200
    stack = np.vstack((np.linspace(0, 256, 256), hist.reshape(-1))).T
    stack[:, 1] = dst.shape[0] - stack[:, 1]
    cv.polylines(dst, [np.int32(stack)], True, (0, 255, 255))

In [6]:
def gamma_alpha_beta():
    img2 = img
    #img2 = adjust_gamma(img, gamma)
    #img2 = cv.convertScaleAbs(img2, alpha = alpha, beta = beta)
    histogram = np.zeros((200, 256, 3), np.uint8)
    imgGray = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)
    plotHist(imgGray, histogram)
    imgGray = cv.equalizeHist(imgGray)
    histogram_eq = np.zeros((200, 256, 3), np.uint8)
    plotHist(imgGray, histogram_eq)
    cv.imshow("Pic", img2)
    cv.imshow("equalized", imgGray)
    cv.imshow("Hist", histogram)
    cv.imshow("equalizedHist", histogram_eq)
def gammaf(val):
    global gamma 
    gamma = val/128
    gamma_alpha_beta()
    
def alphaf(val):
    global alpha 
    alpha= val
    gamma_alpha_beta()
    
def betaf(val):
    global beta 
    beta = val
    gamma_alpha_beta()

In [7]:
cv.imshow("Pic", img)
cv.createTrackbar('gamma', "Pic", 0, 255, gammaf)
cv.createTrackbar('alpha', "Pic", 0, 255, alphaf)
cv.createTrackbar('beta', "Pic", 0, 255, betaf)
cv.waitKey(0)
cv.destroyAllWindows()

## Task5

In [119]:
import numpy as np
import cv2 as cv
import os
import random
img = cv.imread("Task5.png")
img2 = cv.imread("Task5.png")

In [171]:
noise = 15#int(float(input()))
pic_number = 10
img = np.float64(img)
noise_pic = np.copy(img)
a = list()
for k in range(pic_number):
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            noise_val = random.randint(-noise, noise)
            noise_pic[i][j] = img[i][j] + noise_val
    a.append(np.copy(noise_pic))

In [175]:
result = np.asarray([np.add.reduce(i) for i in zip(*a)])
result = (result/(pic_number)).astype('uint8')


In [176]:
cv.imshow("Pic", result)
cv.imshow("Pic2", img2)
cv.waitKey(0)
cv.destroyAllWindows()

In [179]:
for i in range(pic_number):
    cv.imshow("Pic" + str(i), np.uint8(a[i]))
cv.waitKey(0)
cv.destroyAllWindows()

In [153]:
for i in range(5):
    print(a[i][50][50])
print(result[50][50])
print(img[50][50])

[55 55 55]
[54 54 54]
[46 46 46]
[51 51 51]
[48 48 48]
[47 47 47]
[39 39 39]


# Task 6

## Инициализация

In [1]:
import numpy as np
import cv2 as cv
import os
import random

In [2]:
max_lowThreshold = 100
title_trackbar_1 = 'Min Threshold:'
title_trackbar_2 = 'Max Threshold:'
ratio = 3
kernel_size = 3
# colors
red_color = (0, 0, 255)
green_color = (0, 255, 0)
orange_color = (0, 128, 255)
purple_color = (157,0, 90)
blue_color = (255, 0, 0)
magenta_color = (255, 0, 255)
# bar variable 
low_threshold = 100
max_threshold = 100

max_level_contour = 0
treshold_filter_level = 0
exercise = 0

In [3]:
img = cv.imread("Task6-3.png")

In [4]:
def task_six_zero_clear():
    return img.copy()


## Задание 6-0
### Реализовать функцию фильтра Кенни

In [5]:
def CannyFilter(img, low_threshold, max_threshold):
    img_blur = cv.blur(img, (3,3))
    detected_edges = cv.Canny(img_blur, low_threshold, max_threshold, kernel_size)
    mask = detected_edges != 0
    canny_result = img * (mask[:,:,None].astype(img.dtype))
    return detected_edges, canny_result

def task_six_zero_Canny(dst):
    return dst.copy()

## Задание 6-1
### Написать программу, выделяющую границы объектов методом Кэнни
Реализовать выделение контуров объектов по изображению границ,
полученному методом Кэнни для произвольного изображения, а также их
визуализацию поверх исходного изображения.

• Детектор границ Кэнни (cv::Canny)

• Обнаружение и отрисовка контуров (cv:: findContours, cv::drawContours)

In [6]:
def task_six_one(img2, contours, hierarchy):
    cv.drawContours(img2, contours, -1, (0,255,0), 3, cv.LINE_AA, hierarchy, 1)
    for c in contours:
        x, y, w, h = cv.boundingRect(c)
        rect_color = green_color
        cv.rectangle(img2, (x, y), (x + w, y + h), rect_color, 1)
    return img2

## Задание 6.2
### Написать программу, которая автоматически определяет для одного объекта, выделенного методом Кэнни размер объекта (маленький, средний, большой) относительно общего размера изображения
Выставлены ограничения при которых если площадь больше 5% - окрас квадрата зелёный, иначе если больше 3%(от 3% до 5%) - окрас оранжевый, иначе (от 0% до 3%) - окрас красный.

In [7]:
def task_six_two(img2, contours):
    x_img = img.shape[0]
    y_img = img.shape[1]
    square_img_s = x_img * y_img 
    for c in contours:
        x, y, w, h = cv.boundingRect(c)
        rect_color = red_color
        rect_size = w * h
        if rect_size >= (square_img_s / 20.):
            rect_color = green_color
        elif rect_size >= (square_img_s / 30.):
            rect_color = orange_color
        else:
            rect_color = red_color
        cv.rectangle(img2, (x, y), (x + w, y + h), rect_color, 1)
    return img2

## Задание 6.3 
### Написать программу, которая автоматически определяет для одного объекта, выделенного методом Кэнни форму объекта (кравдрат, прямоугольник, треугольник, круг, овал)
Написана функция, которая возвращает имя найденной фигуры. Каждая фигура обводится своим цветом:

Квадрат - зелёным;

Прямоугольник - оранжевым;

Треугольник - красным;

Круг - фиолетовым;

Овал - синим;

Пятиугольник - маджента;

Шестиугольник - белым.



In [8]:
#Return approximated contour
def approximate_contour(contour):
    epsilon  =  0.02 * cv.arcLength(contour, True)
    approximate = cv.approxPolyDP(contour, epsilon, True)
    return approximate

#Return length of vector
def vector_len(v):
    v = np.reshape(v, -1)
    return np.sqrt(v[0] ** 2 + v[1] ** 2)

#Return difference between two vectors
def diff(x, y):
    x = x.ravel()
    y = y.ravel()
    return [x[0] - y[0], x[1] - y[1]]

#Return the name of the shape
def find_shape(contour):
    approximate = approximate_contour(contour)
    if len(approximate) == 3:
        shape = "triangle"
    elif len(approximate) == 4:
        (x, y, w, h) = cv.boundingRect(approximate)
        figure_area = cv.contourArea(approximate)
        approximate_area = vector_len(diff(approximate[0], approximate[1])) ** 2
        area = figure_area / approximate_area
        #Give small window for error
        shape = "square" if 0.9 <= area <= 1.2 else "rectangle"
    elif len(approximate) == 5:
        shape = "pentagon"
    elif len(approximate) == 6:
        shape = "hexagon"
    else:
        M = cv.moments(approximate)
        cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])
        radius = vector_len(approximate[0] - (cX, cY))
        approximate_area = np.pi * (radius ** 2)
        figure_area = cv.contourArea(approximate)
        area = approximate_area / figure_area
        if 0.9 <= area <= 1.2:
            shape = "circle"
        else:
            shape = "ellipse"
    return shape

def task_six_three(img2, contours):
    for c in contours:
        x, y, w, h = cv.boundingRect(c)
        rect_name = find_shape(c)
        rect_color = (0,0,0)
        if rect_name == "square":
            rect_color = green_color
        elif rect_name == "rectangle":
            rect_color = orange_color
        elif rect_name == "triangle":
            rect_color = red_color
        elif rect_name == "circle":
            rect_color = purple_color
        elif rect_name == "ellipse":
            rect_color = blue_color
        elif rect_name == "pentagon":
            rect_color = magenta_color
        elif rect_name == "hexagon":
            rect_color = (255, 255, 255)
        cv.rectangle(img2, (x, y), (x + w, y + h), rect_color, 1)
    return img2

## GUI

In [9]:
# Cutting contours noise
def filter_contours(contours, tresh):
    filtered = []
    for c in contours:
        approx = approximate_contour(c)
        if cv.contourArea(approx) > tresh:
            filtered.append(c)
    return filtered

def update():
    global img
    global low_threshold 
    global max_threshold
    global treshold_filter_level
    detected_edges, dst = CannyFilter(img, low_threshold, max_threshold)
    contours, hierarchy = cv.findContours(detected_edges, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_NONE)
    img2 = dst.copy()
    contours = filter_contours(contours, tresh = treshold_filter_level)
    if exercise == 0:
        img2 = task_six_zero_clear()
    elif exercise == 1:
        img2 = task_six_zero_Canny(dst)
    elif exercise == 2:
        img2 = task_six_one(img2, contours, hierarchy)
    elif exercise == 3: 
        img2 = task_six_two(img2, contours)
    elif exercise == 4:
        img2 = task_six_three(img2, contours)
    cv.imshow("Pic", img2)

def CannyThresholdMin(val):
    global low_threshold 
    low_threshold = val
    update()

def CannyThresholdMax(val):
    global max_threshold
    max_threshold = val
    update()

def TresholdFilterLevel(val):
    global treshold_filter_level
    treshold_filter_level = val
    update()

def exercise_f(val):
    global exercise
    exercise = val
    update()

In [11]:
cv.imshow("Pic", img)
cv.createTrackbar(title_trackbar_1, "Pic" , 190, max_lowThreshold*8, CannyThresholdMin)
cv.createTrackbar(title_trackbar_2, "Pic" , 230, max_lowThreshold*8, CannyThresholdMax)
cv.createTrackbar("TresholdFilterLevel", "Pic" , 45, max_lowThreshold*6, TresholdFilterLevel)
cv.createTrackbar("Task type", "Pic" , 1, 4, exercise_f)
cv.waitKey(0)
cv.destroyAllWindows()

# Task 7

In [1]:
import numpy as np
import cv2 as cv
import os
import random

In [2]:
img = cv.imread("Task5.png")
img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

## Задание 7
### Продемонстрировать возможности линейной фильтрации изображений на основе: Гауссова фильтра, медианного, фильтра с произвольным ядром, оператора Собеля, фильтра Лапласа. Продемонстрировать удаление равномерного шума и Гауссова.
• Гауссов(cv::blur) и медианный фильтр (cv::medianBlur).

• Фильтрация произвольной маской (cv::filter2D).

• Выделение границ объектов (cv::Sobel).

• Фильтр Лапласа. Исследовать влияние входных параметров на
результат фильтрации, провести сравнение с фильтром Собеля.

• cv::randn – нормальное распределение, cv::randu – равномерное
распределение.

In [18]:
# Test of filters with kernel = 3
if False:
    cv.imshow("Pic", img)
    cv.imshow("Gauss", cv.blur(img.copy(), (3, 3)))
    kernel_size = 3
    kernel = np.ones((kernel_size, kernel_size), dtype = np.float32)
    kernel /= (kernel_size * kernel_size)
    cv.imshow("filter2D", cv.filter2D(img.copy(), cv.CV_8U, kernel))
    cv.imshow("Sobel", cv.Sobel(cv.blur(img, (3, 3)), cv.CV_64F, 1, 1, ksize = 3))
    cv.imshow("Laplacian", cv.Laplacian(cv.blur(img, (3, 3)), cv.CV_64F, ksize = 3))
    cv.waitKey(0)
    cv.destroyAllWindows()

In [7]:
def make_noise(img, noise_size, is_normal):
    noise = np.zeros(img.shape)
    if is_normal:
        cv.randn(noise, 0,  noise_size)
    else:
        cv.randu(noise, -noise_size, noise_size)
    return noise

def make_noise_img(img, noise_size, is_normal):
    return np.uint8(np.clip(cv.add(np.float64(img), \
        make_noise(img, noise_size, is_normal)), 0, 255)) # Translate img to float, add noise to img(too has float type), clip it to borders of uint8 and translate it to uint8 

def make_filtered_img(noise_img, filter_name, kernel_elem):
    if filter_name == "Origin":
        return img
    elif filter_name == "Gaussian":
        return cv.blur(noise_img, (kernel_elem, kernel_elem))
    elif filter_name == "Median":
        if kernel_elem % 2 != 1:
            kernel_elem += 1
        return cv.medianBlur(noise_img, kernel_elem) # Work only with kernel elem % 2 == 1
    elif filter_name == "Filter2D":
        return cv.filter2D(noise_img, cv.CV_8U, \
        np.ones((kernel_elem, kernel_elem), dtype = np.float64) / (kernel_elem * kernel_elem)) # Generating kernel that has sizes kernel_elem X kernel_elem and each element of this kernel is equal to 1.0 / kernel_elem
    elif filter_name == "Sobel":
        if kernel_elem % 2 != 1:
            kernel_elem += 1
        return cv.Sobel(cv.blur(noise_img, (kernel_elem, kernel_elem)), cv.CV_64F, 1, 1, ksize = kernel_elem) # Work only with kernel elem % 2 == 1
    elif filter_name == "Laplacian":
        if kernel_elem % 2 != 1:
            kernel_elem += 1
        return cv.Laplacian(cv.blur(img, (kernel_elem, kernel_elem)), cv.CV_64F, ksize=kernel_elem) # Work only with kernel elem % 2 == 1
    else:
        return None
def plotHist(img, hist_size = (200, 256, 3)):
    histogram = np.zeros(hist_size, np.uint8)
    hist, bins = np.histogram(img.ravel(), 256, [0, 256])
    hist = hist / hist.max() * 200
    stack = np.vstack((np.linspace(0, 256, 256), hist.reshape(-1))).T
    stack[:, 1] = histogram.shape[0] - stack[:, 1]
    cv.polylines(histogram, [np.int32(stack)], True, (0, 255, 255))
    return histogram
def concat_img_hist():
    return

In [8]:
#For trackbars
is_normal = True
noise_size = 40
kernel_size = 3
filter_names = list(("Origin", "Gaussian", "Median", "Filter2D", "Sobel", "Laplacian"))
filter_type = 0
# Images
noise_img = make_noise_img(img, 40, True)
filtered_img = make_filtered_img(noise_img, filter_names[filter_type], kernel_size)


In [9]:
def update():
    global filtered_img
    global histogram
    filtered_img = make_filtered_img(noise_img, filter_names[filter_type], kernel_size)
    cv.imshow("Histogram", plotHist(filtered_img))
    cv.imshow("Filtered Pic", filtered_img)
    cv.imshow("Noise Pic", noise_img)


def change_noise(val):
    global noise_img
    global noise_size
    noise_size = val
    noise_img = make_noise_img(img, noise_size, is_normal)
    update()


def change_is_normal(val):
    global noise_img
    if val == 1:
        is_normal = True
    else:
        is_normal = False
    noise_img = make_noise_img(img, noise_size, is_normal)
    update()


def change_kernel_size(val):
    global kernel_size
    global filtered_img
    if val > 0:
        kernel_size = val
        update()


def change_filter_type(val):
    global filtered_img
    global filter_type
    filter_type = val
    update()

In [11]:
#Original or filtered image
cv.imshow("Filtered Pic", img)
cv.createTrackbar("Type of Filter","Filtered Pic", 0, 5, change_filter_type)
cv.createTrackbar("Filters kernel size", "Filtered Pic", 3, 30, change_kernel_size)
#Hist of image
cv.imshow("Histogram", plotHist(filtered_img))
#Noise image
cv.imshow("Noise Pic", noise_img)
cv.createTrackbar("noise size", "Noise Pic", 40, 800, change_noise)
cv.createTrackbar("normal/uniform", "Noise Pic", 1, 1, change_is_normal)
cv.waitKey(0)
cv.destroyAllWindows()

# Task 8

## Initialization

In [11]:
import numpy as np
import cv2 as cv
import os
import random

## Задание 8
### Реализовать поиск линий либо окружностей (на выбор) на характерных изображениях, исследовать эффективность при различных параметрах.

In [35]:
img = cv.imread('Task-8.jpg')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
rho_size = 1.0
theta_devide_size = 360
hough_treshold = 200
low_threshold = 50
high_threshold = 150
aperture_size = 3

In [40]:
def update():
    edges = cv.Canny(gray, low_threshold, high_threshold, \
        apertureSize = aperture_size) # work only with 3 or 5
    lines = cv.HoughLinesP(edges, rho_size, np.pi / theta_devide_size, hough_treshold, \
        minLineLength = 10, maxLineGap = 10)
    #lines = cv.HoughLines(edges, rho_size, np.pi / theta_devide_size, hough_treshold)
    res = img.copy()
    for line in lines:
        #rho,theta = line[0]
        #a = np.cos(theta)
        #b = np.sin(theta)
        #x0 = a * rho
        #y0 = b * rho
        ## x1 stores the rounded off value of (r * cos(theta) - 1000 * sin(theta))
        #x1 = int(x0 + 1000 * (-b))
        ## y1 stores the rounded off value of (r * sin(theta)+ 1000 * cos(theta))
        #y1 = int(y0 + 1000 * (a))
        ## x2 stores the rounded off value of (r * cos(theta)+ 1000 * sin(theta))
        #x2 = int(x0 - 1000 * (-b))
        ## y2 stores the rounded off value of (r * sin(theta)- 1000 * cos(theta))
        #y2 = int(y0 - 1000 * (a))
        x1, y1, x2, y2 = line[0]
        cv.line(res, (x1, y1), (x2, y2), (0, 0, 255), 2)
    cv.imshow('image', res)

def change_rho_size(val):
    global rho_size
    if val > 0:
        rho_size = val / 100
        update()


def change_theta_size(val):
    global theta_devide_size
    if val > 0 :
        theta_devide_size = val
        update()


def change_hough_treshold(val):
    global hough_treshold
    hough_treshold = val
    update()


def change_low_treshold(val):
    global low_threshold
    low_threshold = val
    update()


def change_high_threshold(val):
    global high_threshold
    high_threshold = val
    update()

In [42]:
cv.imshow('image', img)
cv.createTrackbar('rho', 'image', 100, 1000, change_rho_size)
cv.createTrackbar('theta', 'image', 360, 360, change_theta_size)
cv.createTrackbar('hough treshold', 'image', 100, 500, change_hough_treshold)
cv.createTrackbar('low treshold', 'image', 50, 500, change_low_treshold)
cv.createTrackbar('high threshold', 'image', 150, 500, change_high_threshold)
cv.waitKey(0)
cv.destroyAllWindows()

# Task 9

In [129]:
import numpy as np
import cv2 as cv
import os
import random

## Задача 9. 
### Использовать детектор углов Харриса и детектор особыхточек Ши-Томаси, исследовать влияние преобразований изображений (аффинные и перспективные преобразования, изменение яркости, контраста), а также параметров алгоритмов на результаты обнаружения локальных особенностей
1.Harris corner detector
(cv::cornerHarris);

2.Shi-Tomachi
(cv::goodFeaturesToTrack);

3.Преобразования
изображений
(cv::warpAffine,
cv::warpPerspective)

In [130]:
img = cv.imread('Task-9.jpg')
harris_img = img.copy()
shi_tomachi_img = img.copy()
rotated_img = img
#
bright_size = 10
contrast_size = 10
angle_size = 0.0
scale_size = 1.0
marker_list = list()
marker_list.append(cv.MARKER_CROSS)
marker_list.append(cv.MARKER_DIAMOND)
marker_list.append(cv.MARKER_SQUARE)
marker_list.append(cv.MARKER_STAR)
marker_list.append(cv.MARKER_TILTED_CROSS)
marker_list.append(cv.MARKER_TRIANGLE_DOWN)
marker_list.append(cv.MARKER_TRIANGLE_UP)
marker_type = 2
marker_size = 2
# For affine
height, width = img.shape[:2]
center = (width / 2, height / 2)
# For perpective
point_list=list()
point_list.append((0, 0))
point_list.append((img.shape[1], 0))
point_list.append((img.shape[1], img.shape[0]))
point_list.append((0, img.shape[0]))
point_for_change = 0
# For Harris 
block_size = 2
k_size = 3
k_p = 0.001
show_gray_har = 0
# For Shi_Tomachi
corners_count = 80
corners_quality = 0.05
minimal_distance = 5
show_gray_shi = 0


In [131]:
def update():
    global rotated_img
    rotated_img = img.copy()
    change_brightness(bright_size)
    change_contrast(contrast_size)
    rotate_matrix = cv.getRotationMatrix2D(center, angle_size, scale_size)
    rotated_img = cv.warpAffine(rotated_img, rotate_matrix, (width, height))
    matrix = cv.getPerspectiveTransform( np.float32([[0, 0], [img.shape[1], 0], [img.shape[1], img.shape[0]], [0, img.shape[0]]]), \
         np.float32(point_list))
    rotated_img = cv.warpPerspective(rotated_img, matrix, (img.shape[1], img.shape[0]), cv.INTER_CUBIC, borderMode = cv.BORDER_CONSTANT, borderValue = (0, 0, 0))
    cv.imshow('Pic', rotated_img)
    update_Harris()
    update_Shi_tomachi()


def change_brightness( brightness):
    global rotated_img
    if brightness != 0:
        rotated_img = cv.addWeighted(rotated_img, (255 - brightness) / 255, rotated_img, 0, brightness)



def change_contrast( contrast):
    global rotated_img
    if contrast != 0:
        f = 131 * (contrast + 127) / (127 * (131 - contrast))
        rotated_img = cv.addWeighted(rotated_img, f, rotated_img, 0, 127 * (1 - f))


def change_brightness_size(val):
    global bright_size
    bright_size = val
    update()


def change_contrast_size(val):
    global contrast_size
    contrast_size = val
    update()


def change_rotate_angle(val):
    global angle_size
    angle_size = val
    update()


def change_rotate_scale(val):
    global scale_size
    if val > 0:
        scale_size = val / 10.0
        update()


def change_point_for_changing(val):
    global point_for_change
    point_for_change = val


def change_point_x_val(val):
    global point_list
    _, old_y = point_list[point_for_change]
    point_list[point_for_change] = (val, old_y)
    update()   


def change_point_y_val(val):
    global point_list
    old_x, _ = point_list[point_for_change]
    point_list[point_for_change] = (old_x, val)
    update() 

    
def return_to_default(val):
    global point_list
    global scale_size
    global angle_size
    global contrast_size
    global bright_size
    scale_size = 1
    angle_size = 0
    point_list[0] = (0, 0)
    point_list[1] = (img.shape[1], 0)
    point_list[2] = (img.shape[1], img.shape[0])
    point_list[3] = (0, img.shape[0])
    update()


In [132]:
def update_Harris(gray = None):
    gray = cv.cvtColor(rotated_img, cv.COLOR_BGR2GRAY)
    corners = cv.cornerHarris(gray, block_size, k_size, k_p)
    harris_img = rotated_img.copy()
    if show_gray_har == 0:
        harris_img[corners > 0.01 * corners.max()] = [0, 255, 0]
        cv.imshow('Harris', harris_img)
    else:
        harris_img[corners > 0.01 * corners.max()] = [0, 0, 255]
        cv.imshow('Harris', harris_img)

def change_block_size(val):
    global block_size
    block_size = val
    update_Harris()


def change_k_size(val):
    global k_size
    if val % 2 == 0:
        val += 1
    k_size = val
    update_Harris()


def change_k_p(val):
    global k_p
    if val > 0:
        k_p = val / 100
        update_Harris()


def change_res_col_h(val):
    global show_gray_har
    show_gray_har = val
    update_Harris()

In [133]:
def draw_markers_shi(img_, corners, color =  (0, 255, 0)):
    corners_int = np.int0(corners)
    for corner in corners_int:
        x, y = corner.ravel()
        cv.drawMarker(img_, (x, y), color, marker_list[marker_type], marker_size)


def update_Shi_tomachi():
    gray = cv.cvtColor(rotated_img, cv.COLOR_BGR2GRAY)
    corners = cv.goodFeaturesToTrack(gray, corners_count, corners_quality, minimal_distance, mask = cv.inRange(gray, 1, 255))
    shi_tomachi_img = rotated_img.copy()
    if show_gray_shi == 0:
        draw_markers_shi(shi_tomachi_img, corners)
        cv.imshow('Shi tomachi', shi_tomachi_img)
    else:
        draw_markers_shi(shi_tomachi_img, corners, (0, 0, 255))
        cv.imshow('Shi tomachi', shi_tomachi_img)

def change_corners_count(val):
     global corners_count
     if val > 0:
         corners_count = val
         update_Shi_tomachi()


def change_corners_quality(val):
    global corners_quality
    if val > 0:
        corners_quality = val / 100.0
        update_Shi_tomachi()


def change_minimal_distance(val):
    global minimal_distance
    minimal_distance = val
    update_Shi_tomachi()

def change_res_col_shi(val):
    global show_gray_shi
    show_gray_shi = val
    update_Shi_tomachi()


def change_marker_type(val):
    global marker_type
    marker_type = val
    update_Shi_tomachi()


def change_marker_size(val):
    global marker_size
    marker_size = val
    update_Shi_tomachi()

In [136]:
# Do some things with begin pic
cv.imshow('Pic', img)
cv.namedWindow('Control')
cv.createTrackbar('Brightness', 'Control', 0, 255, change_brightness_size)
cv.createTrackbar('Contrast', 'Control', 0, 128, change_contrast_size)
cv.createTrackbar('Angle', 'Control', 0, 360, change_rotate_angle)
cv.createTrackbar('Scale', 'Control', 10, 360, change_rotate_scale)
cv.createTrackbar('Point', 'Control', 0, 3, change_point_for_changing)
cv.createTrackbar('X', 'Control', 0, img.shape[1] - 1, change_point_x_val)
cv.createTrackbar('Y', 'Control', 0, img.shape[0] - 1, change_point_y_val)
cv.namedWindow('Control2')
cv.createTrackbar('Return', 'Control2', 0, 1, return_to_default)
#Harris corners
cv.imshow('Harris', harris_img)
cv.createTrackbar('block size', 'Harris', 2, 50, change_block_size)
cv.createTrackbar('kernel size', 'Harris', 3, 31, change_k_size)
cv.createTrackbar('k', 'Harris', 10, 100, change_k_p)
cv.createTrackbar('is gray', 'Harris', 0, 1, change_res_col_h)
#Shi tomachi corners
cv.imshow('Shi tomachi', shi_tomachi_img)
cv.createTrackbar('corners count', 'Shi tomachi', 80, 300, change_corners_count)
cv.createTrackbar('quality', 'Shi tomachi', 5, 100, change_corners_quality)
cv.createTrackbar('min distance', 'Shi tomachi', 5, 100, change_minimal_distance)
cv.createTrackbar('is gray', 'Shi tomachi', 0, 1, change_res_col_shi)
cv.createTrackbar('Marker type', 'Shi tomachi', 0, len(marker_list) - 1, change_marker_type)
cv.createTrackbar('Marker size', 'Shi tomachi', 2, 30, change_marker_size)

cv.waitKey(0)
cv.destroyAllWindows()

# Task 10

In [2]:
from __future__ import print_function
import numpy as np
import cv2 as cv

## Задача 10. 
### Реализовать поиск соответствия особых точек на двух изображений (feature matching), исследовать работу в реальных условиях.

In [6]:
MAX_FEATURES = 500
GOOD_MATCH_PERCENT = 0.15

def alignImages(im1, im2):

  # Convert images to grayscale
  im1Gray = cv.cvtColor(im1, cv.COLOR_BGR2GRAY)
  im2Gray = cv.cvtColor(im2, cv.COLOR_BGR2GRAY)

  # Detect ORB features and compute descriptors.
  orb = cv.ORB_create(MAX_FEATURES)
  keypoints1, descriptors1 = orb.detectAndCompute(im1Gray, None)
  keypoints2, descriptors2 = orb.detectAndCompute(im2Gray, None)

  # Match features.
  matcher = cv.DescriptorMatcher_create(cv.DESCRIPTOR_MATCHER_BRUTEFORCE_HAMMING)
  matches = matcher.match(descriptors1, descriptors2, None)

  # Sort matches by score
  matches.sort(key=lambda x: x.distance, reverse=False)

  # Remove not so good matches
  numGoodMatches = int(len(matches) * GOOD_MATCH_PERCENT)
  matches = matches[:numGoodMatches]

  # Draw top matches
  imMatches = cv.drawMatches(im1, keypoints1, im2, keypoints2, matches, None)
  cv.imshow("Matches", imMatches)

  # Extract location of good matches
  points1 = np.zeros((len(matches), 2), dtype=np.float32)
  points2 = np.zeros((len(matches), 2), dtype=np.float32)

  for i, match in enumerate(matches):
    points1[i, :] = keypoints1[match.queryIdx].pt
    points2[i, :] = keypoints2[match.trainIdx].pt

  # Find homography
  h, mask = cv.findHomography(points1, points2, cv.RANSAC)

  # Use homography
  height, width, channels = im2.shape
  im1Reg = cv.warpPerspective(im1, h, (width, height))

  return im1Reg, h

In [33]:
#Test 1
# Read reference image
imReference = cv.imread("form.jpg", cv.IMREAD_COLOR)

# Read image to be aligned
im = cv.imread("scanned-form.jpg", cv.IMREAD_COLOR)

In [34]:
# Registered image will be resotred in imReg.
# The estimated homography will be stored in h.
imReg, h = alignImages(im, imReference)
cv.imshow("Full image", imReference)
cv.imshow("Scanned image", im)
cv.waitKey(0)
cv.destroyAllWindows()
# Print estimated homography
print("Estimated homography : \n",  h)

Estimated homography : 
 [[ 7.29442464e-01  9.87380448e-02  1.30465820e+01]
 [-9.45903137e-02  6.60757422e-01  6.59422430e+01]
 [ 1.88339775e-04 -1.86514430e-04  1.00000000e+00]]


In [29]:
#Test 2
# Read reference image
imReference = cv.imread("Colosseo4.jpg", cv.IMREAD_COLOR)

# Read image to be aligned
im = cv.imread("Colosseo2.jpg", cv.IMREAD_COLOR)
imReference =cv.resize(imReference, (im.shape[1], im.shape[0]))

In [30]:
# Registered image will be resotred in imReg.
# The estimated homography will be stored in h.
imReg, h = alignImages(im, imReference)
cv.imshow("Full image", imReference)
cv.imshow("Scanned image", im)
cv.waitKey(0)
cv.destroyAllWindows()
# Print estimated homography
print("Estimated homography : \n",  h)

Estimated homography : 
 [[ 3.24956443e+00 -2.58492189e+00 -2.36415660e+02]
 [ 9.99912775e-01  1.93533459e-01 -1.94959419e+02]
 [ 2.08763439e-03 -3.09567099e-03  1.00000000e+00]]


In [31]:
#Test 3
# Read reference image
imReference = cv.imread("Lays1.png", cv.IMREAD_COLOR)

# Read image to be aligned
im = cv.imread("Lays2.jpg", cv.IMREAD_COLOR)

In [32]:
# Registered image will be resotred in imReg.
# The estimated homography will be stored in h.
imReg, h = alignImages(im, imReference)
cv.imshow("Full image", imReference)
cv.imshow("Scanned image", im)
cv.waitKey(0)
cv.destroyAllWindows()
# Print estimated homography
print("Estimated homography : \n",  h)

Estimated homography : 
 [[ 6.50327264e-01  9.02902079e-02 -3.57634986e+01]
 [-5.43999893e-02  6.98701225e-01 -7.97120521e+01]
 [ 7.24375156e-05  1.92390043e-04  1.00000000e+00]]


# Task 11

In [61]:
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
from scipy.ndimage import label


img = cv.imread("segmentation.jpg")
img = cv.resize(img, (800, 800))
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
ret, img_morph = cv.threshold(gray, 0, 255, cv.THRESH_OTSU)
img_morph = cv.morphologyEx(img_morph, cv.MORPH_OPEN, np.ones((3, 3), dtype=int))
img_copy = img.copy()

In [62]:
low_threshold = 0
high_threshold = 0
iteration_num = 5
ret, thresh = cv.threshold(gray, 20, 255, cv.THRESH_BINARY_INV + cv.THRESH_OTSU)

def update():
    global ret
    global thresh
    # delitating image
    dilated_img = cv.dilate(img_morph, None, iterations = iteration_num)
    dilated_img = dilated_img - cv.erode(dilated_img, None)
    distances_transform = cv.distanceTransform(img_morph, cv.DIST_L2, 3)
    # show distances_transform
    cv.imshow('distances', distances_transform)
    distances_transform = ((distances_transform - distances_transform.min()) / (distances_transform.max() - distances_transform.min()) * 255).astype(np.uint8)
    ret, distances_transform = cv.threshold(distances_transform, low_threshold, high_threshold, cv.THRESH_BINARY)
    # show thresh changing
    cv.imshow("thresh", distances_transform)
    label_, num_features = label(distances_transform)
    # Multiplying label array on 255 / (number of featuter + 1) to prevent deviding on zero
    label_ = label_ * (255 / (num_features + 1))
    # Completing the markers now.
    label_[dilated_img == 255] = 255
    # Using watershed
    label_ = label_.astype(np.int32)
    labels = cv.watershed(img, label_)
    cv.imshow('labels', cv.convertScaleAbs(labels))
    # Changing values that is equal -1
    label_[label_ == -1] = 0
    # Getting outlines as result
    markers = 255 - label_.astype(np.uint8)
    markers[markers != 255] = 0
    markers = cv.dilate(markers, None)
    #copy original image to add on it edges
    result = img.copy()
    result[markers == 255] = (0, 255, 0)
    cv.imshow('Outlines', markers)
    cv.imshow('Result', result)

def change_low_treshold(val):
    global low_threshold
    low_threshold = val
    update()

def change_high_treshold(val):
    global high_threshold
    high_threshold = val
    update()

def change_iteration_num(val):
    global iteration_num
    iteration_num = val
    update()

In [63]:
cv.imshow("thresh", thresh)
cv.createTrackbar('thresh low', 'thresh', 20, 500, change_low_treshold)
cv.createTrackbar('thresh high', 'thresh', 255, 500, change_high_treshold)
cv.createTrackbar('iterations', 'thresh', 5, 100, change_iteration_num)
cv.waitKey(0)
cv.destroyAllWindows()

# Task 12.4

## First try

In [1]:
import cv2 as cv
from mtcnn import MTCNN
from deepface import DeepFace
from deepface.basemodels import VGGFace, OpenFace, Facenet, FbDeepFace
import matplotlib.pyplot as plt
import os
detector = MTCNN() # создание детектора

In [2]:
def detect_faces(img):
    result = detector.detect_faces(img)  # обнаружение лиц на изображении
    faces_list = list()
    boundings = list()
    for i in range(len(result)): 
        bounding_box = result[i]['box']  #  ограничивающие рамки
        faces_list.append(img[bounding_box[1]: bounding_box[1] + bounding_box[3], bounding_box[0]:bounding_box[0] + bounding_box[2]])
        boundings.append(result[i]['box'])
        #cv.rectangle(image, (bounding_box[0], bounding_box[1]),
        #(bounding_box[0]+bounding_box[2], bounding_box[1] + bounding_box[3]),(0,155,255), 2) #  ограничение области на изображении      
    return faces_list, boundings
def get_img_stats(img_path):
    pred = DeepFace.analyze(img_path = img_path,  enforce_detection = False, actions = ['emotion', 'age', 'gender', 'race'])
    return pred
    #for key in pred['emotion']:
    #    if pred['emotion'][key] > 10:
    #        print(key, int(pred['emotion'][key]), "%") 
    #print("Age:", pred['age'])
    #print("Sex:", pred['gender'])
    #for key in pred['race']:
    #    if pred['race'][key] > 10:
    #        print(key, int(pred['race'][key]), "%")

def save_faces(faces):
    save_file_names = list()
    for i in range(len(faces)):
        save_file_names.append("face"+str(i)+".jpg")
        cv.imwrite(save_file_names[i], faces[i])
    return save_file_names

def delete_faces(face_pathes):
    for i in range(len(face_pathes)):
        os.remove(face_pathes[i])

def show_age_and_gender(img_path):
    img = cv.imread(img_path)
    img2 = cv.cvtColor(img, cv.COLOR_BGR2RGB)
    faces, bound = detect_faces(img2)
    save_pathes = save_faces(faces)
    face_pred = list()
    text_add_move = 30
    for i in range(len(save_pathes)):
        text_move = text_add_move
        face_pred.append(get_img_stats(save_pathes[i]))
        bounding_box = bound[i]
        cv.rectangle(img, (bounding_box[0], bounding_box[1]),
        (bounding_box[0] + bounding_box[2], bounding_box[1] + bounding_box[3]),(0,255,0), 2) #  ограничение области на изображении      
        font = cv.FONT_HERSHEY_SIMPLEX
        for key in face_pred[i]['emotion']:
            if face_pred[i]['emotion'][key] > 10:
                cv.putText(img, (key +" "+ str(int(face_pred[i]['emotion'][key]))+"%"), 
                (bounding_box[0] + 10, bounding_box[1] + text_move), 
                font, 1, (0, 0, 0), 2, cv.LINE_AA)
                cv.putText(img, (key +" "+ str(int(face_pred[i]['emotion'][key]))+"%"), 
                (bounding_box[0] + 10, bounding_box[1] + text_move), 
                font, 1, (0, 255, 0), 1, cv.LINE_AA)
                text_move += text_add_move
        cv.putText(img, ("Age:" + str(face_pred[i]['age'])), 
                (bounding_box[0] + 10, bounding_box[1] + text_move), 
                font, 1, (0, 0, 0), 2, cv.LINE_AA)
        cv.putText(img, ("Age:" + str(face_pred[i]['age'])), 
                (bounding_box[0] + 10, bounding_box[1] + text_move), 
                font, 1, (0, 255, 0), 1, cv.LINE_AA)
        text_move+=text_add_move
        cv.putText(img, ("Sex:" + str(face_pred[i]['gender'])), 
                (bounding_box[0] + 10, bounding_box[1] + text_move), 
                font, 1, (0, 0, 0), 2, cv.LINE_AA)
        cv.putText(img, ("Sex:" + str(face_pred[i]['gender'])), 
                (bounding_box[0] + 10, bounding_box[1] + text_move), 
                font, 1, (0, 255, 0), 1, cv.LINE_AA)
        text_move += text_add_move
        for key in face_pred[i]['race']:
            if face_pred[i]['race'][key] > 10:
                cv.putText( img,  (str(key) + " " + str(int(face_pred[i]['race'][key]))+"%"), 
                (bounding_box[0] + 10, bounding_box[1] + text_move), 
                font, 1, (0, 0, 0), 2, cv.LINE_AA)
                cv.putText( img,  (str(key) + " " + str(int(face_pred[i]['race'][key]))+"%"), 
                (bounding_box[0] + 10, bounding_box[1] + text_move), 
                font, 1, (0, 255, 0), 1, cv.LINE_AA)
                text_move += text_add_move
    delete_faces(save_pathes)
    cv.imshow("Pic", img)

In [6]:
pictures = ['task12.jpeg', 'task12.jpg', 'task12-1.jpg', 'task12-2.jpg', 'task12-3.jpg', 'task12-4.jpg', 'task12-5.jpg', 'task12-6.png']
for i in pictures:   
    show_age_and_gender(i)
    cv.waitKey(0)
    cv.destroyAllWindows()

Action: race: 100%|██████████| 4/4 [00:00<00:00, 10.07it/s]


In [111]:
show_age_and_gender()
cv.waitKey(0)
cv.destroyAllWindows()

Action: race: 100%|██████████| 4/4 [00:00<00:00,  9.64it/s]


In [112]:
show_age_and_gender('task12-1.jpg')
cv.waitKey(0)
cv.destroyAllWindows()

Action: race: 100%|██████████| 4/4 [00:00<00:00,  9.83it/s]


In [113]:
show_age_and_gender('task12-2.jpg')
cv.waitKey(0)
cv.destroyAllWindows()

Action: race: 100%|██████████| 4/4 [00:00<00:00,  9.85it/s]


In [114]:
show_age_and_gender('task12-3.jpg')
cv.waitKey(0)
cv.destroyAllWindows()